name: CI for project

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          cat > .env << EOF
          DB_HOST=${{ secrets.DB_HOST }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          POSTGRES_SSLMODE=${{ secrets.POSTGRES_SSLMODE }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_PORT=${{ secrets.SMTP_PORT }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
          FILE_WITH_BIG_NUMS=${{ secrets.FILE_WITH_BIG_NUMS }}
          EOF
      - name: Show file was created
        run: |
          echo "File created:"
          ls -la .env
          echo "File exists!"  

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

  build:
    runs-on: ubuntu-latest
    needs: create-env-file
    steps:
      - uses: actions/checkout@v3

      - name: Download .env file
        uses: actions/download-artifact@v4
        with:
          name: env-file
          path: ./internal/config/

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.3'

      - name: Start databases on Docker
        run: docker compose up -d

      - name: Build
        run: go build -o trinity cmd/trinity/main.go

      - name: run service
        run: timeout 10s ./trinity || true